# This makefile uses Babel (with the React
# extension) to translate the EcmaScript 5 source
# files into browser compatible JavaScript.

all: vehicles.js

vehicles.js: vehicles.babel
	babel vehicles.babel -o vehicles.js
