# This makefile uses Babel (with the React
# extension) to translate the EcmaScript 5 source
# files into browser compatible JavaScript.

all: apply_block clients hero services vehicles

apply_block:
	$(MAKE) -C apply_block

clients:
	$(MAKE) -C clients

hero:
	$(MAKE) -C hero

services:
	$(MAKE) -C services

vehicles:
	$(MAKE) -C vehicles
