# This makefile uses Babel (with the React
# extension) to translate the EcmaScript 5 source
# files into browser compatible JavaScript.

all: apply_block vehicles

apply_block:
	$(MAKE) -C apply_block

vehicles:
	$(MAKE) -C vehicles
